#ifndef __ELEMENTS_H
#define __ELEMENTS_H

#include "gconio.h"

#define SUPEREF 2.0f
#define EFFECTI 1.0f
#define NOTEFFE 0.5f
#define IMUNITY 0.0f

const float elementMatrix[19][19] = {
//            NUL      NOR      FIR      WAT      ELE      GRA      ICE      FIG      POI      GRD      FLY      PSY      BUG      ROC      GHO      DRA      DAR      STE      FAI
/* NUL */ { EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI },
/* NOR */ { EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, IMUNITY, EFFECTI, EFFECTI, NOTEFFE, EFFECTI },
/* FIR */ { EFFECTI, EFFECTI, NOTEFFE, NOTEFFE, EFFECTI, SUPEREF, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, NOTEFFE, EFFECTI, NOTEFFE, EFFECTI, SUPEREF, EFFECTI },
/* WAT */ { EFFECTI, EFFECTI, SUPEREF, NOTEFFE, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, EFFECTI },
/* ELE */ { EFFECTI, EFFECTI, EFFECTI, SUPEREF, NOTEFFE, NOTEFFE, EFFECTI, EFFECTI, IMUNITY, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, EFFECTI },
/* GRA */ { EFFECTI, EFFECTI, NOTEFFE, SUPEREF, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, SUPEREF, NOTEFFE, EFFECTI, NOTEFFE, SUPEREF, EFFECTI, NOTEFFE, EFFECTI, NOTEFFE, EFFECTI },
/* ICE */ { EFFECTI, EFFECTI, NOTEFFE, NOTEFFE, EFFECTI, SUPEREF, NOTEFFE, EFFECTI, SUPEREF, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, NOTEFFE, EFFECTI },
/* FIG */ { EFFECTI, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, NOTEFFE, NOTEFFE, NOTEFFE, SUPEREF, IMUNITY, EFFECTI, SUPEREF, SUPEREF, NOTEFFE },
/* GRD */ { EFFECTI, EFFECTI, SUPEREF, EFFECTI, SUPEREF, NOTEFFE, EFFECTI, EFFECTI, EFFECTI, IMUNITY, EFFECTI, NOTEFFE, SUPEREF, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI },
/* FLY */ { EFFECTI, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, SUPEREF, EFFECTI, SUPEREF, EFFECTI, EFFECTI, EFFECTI, SUPEREF, NOTEFFE, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, EFFECTI },
/* PSY */ { EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, EFFECTI, EFFECTI, IMUNITY, NOTEFFE, EFFECTI },
/* BUG */ { EFFECTI, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, SUPEREF, EFFECTI, NOTEFFE, EFFECTI, NOTEFFE, SUPEREF, EFFECTI, EFFECTI, NOTEFFE, EFFECTI, SUPEREF, NOTEFFE, NOTEFFE },
/* ROC */ { EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, EFFECTI, SUPEREF, NOTEFFE, NOTEFFE, SUPEREF, EFFECTI, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, EFFECTI },
/* GHO */ { EFFECTI, IMUNITY, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, SUPEREF, EFFECTI, NOTEFFE, EFFECTI, EFFECTI },
/* DRA */ { EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, NOTEFFE, IMUNITY },
/* DAR */ { EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, SUPEREF, EFFECTI, NOTEFFE, EFFECTI, NOTEFFE },
/* STE */ { EFFECTI, EFFECTI, NOTEFFE, NOTEFFE, NOTEFFE, SUPEREF, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, SUPEREF },
/* FAI */ { EFFECTI, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, SUPEREF, NOTEFFE, EFFECTI }
};

/*
0-NULL
1-NORMAL    2-FIRE      3-WATER     4-ELETRIC   5-GRASS     6-ICE       7-FIGHTINING    8-GROUND
9-FLYING   10-PSYCHIC  11-BUG      12-ROCK     13-GHOST    14-DRAGON   15-DARK         16-STEEL    17-FAIRY
*/

enum elementColor{
    nullElement = 0;
    normal = WHITE,
    fire = RED,
    water = BLUE,
    eletric = YELLOW,
    grass = GREEN,
    ice = CYAN,
    fightining = BLACK,
    ground = BROWN,
    flying = LIGHTGRAY,
    psychic = MAGENTA,
    bug = LIGHTGREEN,
    rock = DARKGRAY,
    ghost = LIGHTRED,
    dragon = LIGHTBLUE,
    dark = DARKGRAY,
    steel = LIGHTCYAN,
    fairy = LIGHTMAGENTA,
};

// 0-PHY 1-SPE

float ElementEffectiviness(enum element attacker, enum element targetFirst, enum element targetSecond){
    return elementMatrix[attacker][targetFirst] * elementMatrix[attacker][targetSecond];
}

#endif
