#ifndef __ELEMENTS_H
#define __ELEMENTS_H

#define SUPEREF 2.0f
#define EFFECTI 1.0f
#define NOTEFFE 0.5f
#define IMUNITY 0.0f

const float elementMatrix[19][19] = {
//            NUL      NOR      FIR      WAT      ELE      GRA      ICE      FIG      POI      GRD      FLY      PSY      BUG      ROC      GHO      DRA      DAR      STE      FAI
/* NUL */ { EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI },
/* NOR */ { EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, IMUNITY, EFFECTI, EFFECTI, NOTEFFE, EFFECTI },
/* FIR */ { EFFECTI, EFFECTI, NOTEFFE, NOTEFFE, EFFECTI, SUPEREF, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, NOTEFFE, EFFECTI, NOTEFFE, EFFECTI, SUPEREF, EFFECTI },
/* WAT */ { EFFECTI, EFFECTI, SUPEREF, NOTEFFE, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, EFFECTI },
/* ELE */ { EFFECTI, EFFECTI, EFFECTI, SUPEREF, NOTEFFE, NOTEFFE, EFFECTI, EFFECTI, EFFECTI, IMUNITY, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, EFFECTI },
/* GRA */ { EFFECTI, EFFECTI, NOTEFFE, SUPEREF, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, NOTEFFE, SUPEREF, NOTEFFE, EFFECTI, NOTEFFE, SUPEREF, EFFECTI, NOTEFFE, EFFECTI, NOTEFFE, EFFECTI },
/* ICE */ { EFFECTI, EFFECTI, NOTEFFE, NOTEFFE, EFFECTI, SUPEREF, NOTEFFE, EFFECTI, EFFECTI, SUPEREF, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, NOTEFFE, EFFECTI },
/* FIG */ { EFFECTI, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, NOTEFFE, EFFECTI, NOTEFFE, NOTEFFE, NOTEFFE, SUPEREF, IMUNITY, EFFECTI, SUPEREF, SUPEREF, NOTEFFE },
/* POI */ { EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, NOTEFFE, NOTEFFE, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, NOTEFFE, EFFECTI, EFFECTI, IMUNITY, SUPEREF },
/* GRD */ { EFFECTI, EFFECTI, SUPEREF, EFFECTI, SUPEREF, NOTEFFE, EFFECTI, EFFECTI, SUPEREF, EFFECTI, IMUNITY, EFFECTI, NOTEFFE, SUPEREF, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI },
/* FLY */ { EFFECTI, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, SUPEREF, EFFECTI, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, NOTEFFE, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, EFFECTI },
/* PSY */ { EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, SUPEREF, EFFECTI, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, EFFECTI, EFFECTI, IMUNITY, NOTEFFE, EFFECTI },
/* BUG */ { EFFECTI, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, SUPEREF, EFFECTI, NOTEFFE, NOTEFFE, EFFECTI, NOTEFFE, SUPEREF, EFFECTI, EFFECTI, NOTEFFE, EFFECTI, SUPEREF, NOTEFFE, NOTEFFE },
/* ROC */ { EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, EFFECTI, SUPEREF, NOTEFFE, EFFECTI, NOTEFFE, SUPEREF, EFFECTI, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, EFFECTI },
/* GHO */ { EFFECTI, IMUNITY, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, SUPEREF, EFFECTI, NOTEFFE, EFFECTI, EFFECTI },
/* DRA */ { EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, NOTEFFE, IMUNITY },
/* DAR */ { EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, SUPEREF, EFFECTI, NOTEFFE, EFFECTI, NOTEFFE },
/* STE */ { EFFECTI, EFFECTI, NOTEFFE, NOTEFFE, NOTEFFE, SUPEREF, SUPEREF, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, EFFECTI, EFFECTI, EFFECTI, NOTEFFE, SUPEREF },
/* FAI */ { EFFECTI, EFFECTI, NOTEFFE, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, NOTEFFE, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, EFFECTI, SUPEREF, SUPEREF, NOTEFFE, EFFECTI }
};

/*
0-NULL
1-NORMAL    2-FIRE      3-WATER     4-ELETRIC   5-GRASS     6-ICE       7-FIGHTINING    8-POISON    9-GROUND 
10-FLYING   11-PSYCHIC  12-BUG      13-ROCK     14-GHOST    15-DRAGON   16-DARK         17-STEEL    18-FAIRY
*/

// 0-PHY 1-SPE

#endif